In [ ]:
import numpy as np

import plotly
import plotly.graph_objects as go
import plotly.express as px

from numpy.linalg import inv

Исходная матрица

In [ ]:
N=100
a=20
A = np.zeros((N,N))
for j in range(N):
  for k in range(N):
    if j==k: A[j,k]=a
    elif j+1==k or j+2==k or j+3==k or j+4==k or j-1==k or j-2==k or j-3==k or j-4==k: A[j,k]=1


F = np.arange(1, 101)[:,np.newaxis]
print(A)

[[20.  1.  1. ...  0.  0.  0.]
 [ 1. 20.  1. ...  0.  0.  0.]
 [ 1.  1. 20. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ... 20.  1.  1.]
 [ 0.  0.  0. ...  1. 20.  1.]
 [ 0.  0.  0. ...  1.  1. 20.]]


Метод Гаусса

In [ ]:
n = 100
a = np.concatenate((A,F), axis=1)
x = np.zeros(n)
# Forward stepping
for i in range(n):        
    for j in range(i+1, n):
        ratio = a[j,i]/a[i,i]
        
        for k in range(n+1):
            a[j,k] = a[j,k] - ratio*a[i,k]

# Back stepping and solutions
x[n-1] = a[n-1,n]/a[n-1,n-1]

for i in range(n-2,-1,-1):
    x[i] = a[i,n]
    
    for j in range(i+1,n):
        x[i] = x[i] - a[i,j]*x[j]
    
    x[i] = x[i]/a[i,i]

# Printing
print('\nРешение: ')
for i in range(n):
    print('X%d = %f' %(i,x[i]), end = '\t')


Решение: 
X0 = 0.025221	X1 = 0.066562	X2 = 0.106037	X3 = 0.143636	X4 = 0.179352	X5 = 0.214515	X6 = 0.249972	X7 = 0.285628	X8 = 0.321383	X9 = 0.357139	X10 = 0.392865	X11 = 0.428578	X12 = 0.464288	X13 = 0.499999	X14 = 0.535714	X15 = 0.571428	X16 = 0.607143	X17 = 0.642857	X18 = 0.678571	X19 = 0.714286	X20 = 0.750000	X21 = 0.785714	X22 = 0.821429	X23 = 0.857143	X24 = 0.892857	X25 = 0.928571	X26 = 0.964286	X27 = 1.000000	X28 = 1.035714	X29 = 1.071429	X30 = 1.107143	X31 = 1.142857	X32 = 1.178571	X33 = 1.214286	X34 = 1.250000	X35 = 1.285714	X36 = 1.321429	X37 = 1.357143	X38 = 1.392857	X39 = 1.428571	X40 = 1.464286	X41 = 1.500000	X42 = 1.535714	X43 = 1.571429	X44 = 1.607143	X45 = 1.642857	X46 = 1.678571	X47 = 1.714286	X48 = 1.750000	X49 = 1.785714	X50 = 1.821429	X51 = 1.857143	X52 = 1.892857	X53 = 1.928571	X54 = 1.964286	X55 = 2.000000	X56 = 2.035714	X57 = 2.071429	X58 = 2.107143	X59 = 2.142857	X60 = 2.178571	X61 = 2.214286	X62 = 2.250000	X63 = 2.285714	X64 = 2.321429	X65 = 2.357143	X66 = 2.3

In [ ]:
F.T-np.matmul(A,x)

array([[ 0.00000000e+00,  0.00000000e+00,  4.44089210e-16,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -1.77635684e-15,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00, -1.77635684e-15, -1.77635684e-15,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  3.55271368e-15,  0.00000000e+00,
         3.55271368e-15, -3.55271368e-15,  0.00000000e+00,
         7.10542736e-15,  0.00000000e+00,  3.55271368e-15,
         0.00000000e+00, -3.55271368e-15,  0.00000000e+00,
        -7.10542736e-15,  0.00000000e+00, -3.55271368e-15,
        -3.55271368e-15,  3.55271368e-15, -7.10542736e-15,
        -7.10542736e-15,  0.00000000e+00,  0.00000000e+00,
        -7.10542736e-15, -7.10542736e-15, -7.10542736e-15,
        -7.10542736e-15, -1.42108547e-14,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00, -7.10542736e-15,
        -7.10542736e-15, -7.10542736e-15,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+0

Метод Зейделя

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/bbc6f19a979c73a7ed081d83a91cf1e32541d47d)

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/f744aa67c880cb11dd1b23b67052751b28da372a)

In [ ]:
def zeidel_iter(A, F, x):
    #A is a system's matrix (2D), and F is a right part vector (1D)
    n = len(A)
    x_new = np.copy(x)

    for i in range(n):
        s1 = sum(A[i][j] * x_new[j] for j in range(i))
        s2 = sum(A[i][j] * x[j] for j in range(i + 1, n))
        x_new[i] = (F[i] - s1 - s2) / A[i][i]

    return x_new
num =30
x = np.zeros(np.shape(A)[0])
for i in range(num):
    x = zeidel_iter(A, F, x)

print('\nSolution is: ')
for i in range(len(A)):
    print('X%d = %f' %(i,x[i]), end = '\t')


Solution is: 
X0 = 0.025221	X1 = 0.066562	X2 = 0.106037	X3 = 0.143636	X4 = 0.179352	X5 = 0.214515	X6 = 0.249972	X7 = 0.285628	X8 = 0.321383	X9 = 0.357139	X10 = 0.392865	X11 = 0.428578	X12 = 0.464288	X13 = 0.499999	X14 = 0.535714	X15 = 0.571428	X16 = 0.607143	X17 = 0.642857	X18 = 0.678571	X19 = 0.714286	X20 = 0.750000	X21 = 0.785714	X22 = 0.821429	X23 = 0.857143	X24 = 0.892857	X25 = 0.928571	X26 = 0.964286	X27 = 1.000000	X28 = 1.035714	X29 = 1.071429	X30 = 1.107143	X31 = 1.142857	X32 = 1.178571	X33 = 1.214286	X34 = 1.250000	X35 = 1.285714	X36 = 1.321429	X37 = 1.357143	X38 = 1.392857	X39 = 1.428571	X40 = 1.464286	X41 = 1.500000	X42 = 1.535714	X43 = 1.571429	X44 = 1.607143	X45 = 1.642857	X46 = 1.678571	X47 = 1.714286	X48 = 1.750000	X49 = 1.785714	X50 = 1.821429	X51 = 1.857143	X52 = 1.892857	X53 = 1.928571	X54 = 1.964286	X55 = 2.000000	X56 = 2.035714	X57 = 2.071429	X58 = 2.107143	X59 = 2.142857	X60 = 2.178571	X61 = 2.214286	X62 = 2.250000	X63 = 2.285714	X64 = 2.321429	X65 = 2.357143	X66 =

In [ ]:
#Невязки
F.T-np.matmul(A,x)

array([[ 0.00000000e+00,  0.00000000e+00,  4.44089210e-16,
         0.00000000e+00,  0.00000000e+00,  8.88178420e-16,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.77635684e-15,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00, -1.77635684e-15,
         3.55271368e-15,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  3.55271368e-15,
        -3.55271368e-15,  0.00000000e+00,  3.55271368e-15,
         0.00000000e+00,  0.00000000e+00, -7.10542736e-15,
        -3.55271368e-15,  3.55271368e-15,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         7.10542736e-15,  0.00000000e+00,  0.00000000e+00,
        -1.42108547e-14, -7.10542736e-15,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -1.42108547e-14,  0.00000000e+00,  0.00000000e+0

Собственные значения

In [ ]:
n = 100
a = np.copy(A)
# Written only for non-zero diag elements
def eigval_reverse(a):
    n = 100
    e = np.eye(n)
    for i in range(n):        
       for j in (np.append(np.arange(i), np.arange(i+1,n))):
            ratio = a[j,i]/a[i,i]
            for k in range(n):
                a[j,k] = a[j,k] - ratio*a[i,k]
                e[j,k] = e[j,k] - ratio*e[i,k]

    return [np.diag(a), (e.T/np.diag(a)).T]


Число обусловленности


In [ ]:
#first of all  reve rse matrix
[EigVal, reverse] = eigval_reverse(A)
[lam1, temp] = eigval_reverse(np.matmul(A,A.T))
[lam2, temp] = eigval_reverse(np.matmul(reverse, reverse.T))
np.sqrt(np.max(lam1)*np.max(lam2))

1.0128894087856393

In [ ]:
lam1

array([400.        , 398.0025    , 396.19954649, 394.56404959,
       393.07372401, 393.01323484, 392.98307229, 392.97224793,
       392.97087344, 392.97013406, 392.96992973, 392.9699031 ,
       392.969903  , 392.96989778, 392.96989705, 392.96989704,
       392.96989701, 392.96989699, 392.96989698, 392.96989698,
       392.96989698, 392.96989698, 392.96989698, 392.96989698,
       392.96989698, 392.96989698, 392.96989698, 392.96989698,
       392.96989698, 392.96989698, 392.96989698, 392.96989698,
       392.96989698, 392.96989698, 392.96989698, 392.96989698,
       392.96989698, 392.96989698, 392.96989698, 392.96989698,
       392.96989698, 392.96989698, 392.96989698, 392.96989698,
       392.96989698, 392.96989698, 392.96989698, 392.96989698,
       392.96989698, 392.96989698, 392.96989698, 392.96989698,
       392.96989698, 392.96989698, 392.96989698, 392.96989698,
       392.96989698, 392.96989698, 392.96989698, 392.96989698,
       392.96989698, 392.96989698, 392.96989698, 392.96